<?php

namespace Database\Seeders;

use App\Models\Device;
use App\Models\User;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    public function run(): void
    {
        $userIds = User::pluck('id')->toArray();

        // ── KOMPUTER ──────────────────────────────────────────────────────────
        $komputer = [
            [
                'type' => 'laptop',
                'hostname' => 'LAPTOP-KPP001',
                'brand' => 'Lenovo',
                'model' => 'ThinkPad E14 Gen 4',
                'serial_number' => 'SN-LNV-2024-001',
                'asset_tag' => 'AST-2024-001',
                'ip_address' => '10.9.1.101',
                'mac_address' => '00:1A:2B:3C:4D:01',
                'os' => 'Windows 11 Pro',
                'os_version' => '22H2',
                'processor' => 'Intel Core i5-1235U',
                'ram' => '16GB DDR4',
                'storage_type' => 'SSD',
                'storage_capacity' => '512GB',
                'location' => 'Lantai 2',
                'responsible_section' => 'Seksi PDI',
                'condition' => 'excellent',
                'status' => 'active',
                'purchase_date' => '2024-01-15',
                'warranty_expiry' => '2027-01-15',
            ],
            [
                'type' => 'desktop',
                'hostname' => 'PC-KPP-PDI-01',
                'brand' => 'Dell',
                'model' => 'OptiPlex 7010',
                'serial_number' => 'SN-DEL-2023-001',
                'asset_tag' => 'AST-2024-002',
                'ip_address' => '10.9.1.102',
                'mac_address' => '00:1A:2B:3C:4D:02',
                'os' => 'Windows 10 Pro',
                'os_version' => '22H2',
                'processor' => 'Intel Core i7-12700',
                'ram' => '32GB DDR4',
                'storage_type' => 'NVMe',
                'storage_capacity' => '1TB',
                'location' => 'Lantai 1',
                'responsible_section' => 'Seksi Pelayanan',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2023-06-01',
                'warranty_expiry' => '2026-06-01',
            ],
            [
                'type' => 'desktop',
                'hostname' => 'PC-KPP-UMUM-01',
                'brand' => 'HP',
                'model' => 'ProDesk 400 G9',
                'serial_number' => 'SN-HP-2023-002',
                'asset_tag' => 'AST-2024-003',
                'ip_address' => '10.9.1.103',
                'mac_address' => '00:1A:2B:3C:4D:03',
                'os' => 'Windows 10 Pro',
                'os_version' => '21H2',
                'processor' => 'Intel Core i5-12500',
                'ram' => '8GB DDR4',
                'storage_type' => 'SSD',
                'storage_capacity' => '256GB',
                'location' => 'Lantai 1',
                'responsible_section' => 'Subbagian Umum',
                'condition' => 'fair',
                'status' => 'active',
                'purchase_date' => '2022-03-10',
                'warranty_expiry' => '2025-03-10',
            ],
            [
                'type' => 'all-in-one',
                'hostname' => 'AIO-KPP-KASUB-01',
                'brand' => 'Apple',
                'model' => 'iMac 24" M3',
                'serial_number' => 'SN-APL-2024-001',
                'asset_tag' => 'AST-2024-004',
                'ip_address' => '10.9.1.110',
                'mac_address' => 'A4:83:E7:AB:CD:EF',
                'os' => 'macOS Sequoia',
                'os_version' => '15.3',
                'processor' => 'Apple M3 8-core',
                'ram' => '16GB Unified',
                'storage_type' => 'SSD',
                'storage_capacity' => '512GB',
                'location' => 'Lantai 3',
                'responsible_section' => 'Pimpinan / Kepala Kantor',
                'condition' => 'excellent',
                'status' => 'active',
                'purchase_date' => '2024-03-01',
                'warranty_expiry' => '2027-03-01',
            ],
            [
                'type' => 'workstation',
                'hostname' => 'WS-KPP-IT-01',
                'brand' => 'HP',
                'model' => 'Z4 G4 Workstation',
                'serial_number' => 'SN-HP-2022-WS01',
                'asset_tag' => 'AST-2024-005',
                'ip_address' => '10.9.1.115',
                'mac_address' => '00:1A:2B:3C:4D:05',
                'os' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'processor' => 'Intel Xeon W-2223',
                'ram' => '64GB DDR4 ECC',
                'storage_type' => 'NVMe',
                'storage_capacity' => '2TB',
                'location' => 'Lantai 2',
                'responsible_section' => 'Seksi IT / PDI',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2022-09-15',
                'warranty_expiry' => '2025-09-15',
            ],
            [
                'type' => 'laptop',
                'hostname' => 'LAPTOP-KPP-RUSAK',
                'brand' => 'Acer',
                'model' => 'Aspire 5',
                'serial_number' => 'SN-ACR-2019-001',
                'asset_tag' => 'AST-2024-006',
                'ip_address' => null,
                'mac_address' => null,
                'os' => 'Windows 10 Home',
                'os_version' => '21H1',
                'processor' => 'Intel Core i3-8130U',
                'ram' => '4GB DDR4',
                'storage_type' => 'HDD',
                'storage_capacity' => '500GB',
                'location' => 'Lantai 2',
                'responsible_section' => 'Seksi IT / PDI (Gudang)',
                'condition' => 'broken',
                'status' => 'maintenance',
                'purchase_date' => '2019-04-20',
                'warranty_expiry' => '2022-04-20',
                'notes' => 'Layar retak, keyboard tidak berfungsi. Menunggu anggaran perbaikan.',
            ],
        ];

        // ── PRINTER / SCANNER ─────────────────────────────────────────────────
        $printers = [
            [
                'type' => 'printer',
                'hostname' => 'PRINTER-LT2-01',
                'brand' => 'Canon',
                'model' => 'imageCLASS MF445dw',
                'serial_number' => 'SN-CAN-2023-PR01',
                'asset_tag' => 'AST-2024-101',
                'ip_address' => '10.9.1.201',
                'printer_connection' => 'Network',
                'printer_function' => 'Print, Scan, Copy',
                'location' => 'Lantai 2',
                'responsible_section' => 'Subbagian Umum',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2023-02-10',
                'warranty_expiry' => '2026-02-10',
            ],
            [
                'type' => 'printer',
                'hostname' => 'PRINTER-LT1-01',
                'brand' => 'Epson',
                'model' => 'EcoTank ET-4850',
                'serial_number' => 'SN-EPS-2022-PR01',
                'asset_tag' => 'AST-2024-102',
                'ip_address' => null,
                'printer_connection' => 'USB',
                'printer_function' => 'Print, Scan, Copy, Fax',
                'location' => 'Lantai 1',
                'responsible_section' => 'Seksi Pelayanan',
                'condition' => 'fair',
                'status' => 'active',
                'purchase_date' => '2022-07-05',
                'warranty_expiry' => '2025-07-05',
                'notes' => 'Tinta warna cyan sering habis.',
            ],
            [
                'type' => 'printer',
                'hostname' => 'PRINTER-LT3-01',
                'brand' => 'HP',
                'model' => 'LaserJet Pro M404dn',
                'serial_number' => 'SN-HP-2023-PR01',
                'asset_tag' => 'AST-2024-103',
                'ip_address' => '10.9.1.202',
                'printer_connection' => 'Network',
                'printer_function' => 'Print',
                'location' => 'Lantai 3',
                'responsible_section' => 'Pimpinan / Kepala Kantor',
                'condition' => 'excellent',
                'status' => 'active',
                'purchase_date' => '2023-08-20',
                'warranty_expiry' => '2026-08-20',
            ],
            [
                'type' => 'scanner',
                'hostname' => 'SCANNER-IT-01',
                'brand' => 'Fujitsu',
                'model' => 'ScanSnap iX1600',
                'serial_number' => 'SN-FUJ-2023-SC01',
                'asset_tag' => 'AST-2024-104',
                'ip_address' => '10.9.1.203',
                'printer_connection' => 'Wireless',
                'printer_function' => 'Scan',
                'location' => 'Lantai 2',
                'responsible_section' => 'Seksi IT / PDI',
                'condition' => 'excellent',
                'status' => 'active',
                'purchase_date' => '2023-11-01',
                'warranty_expiry' => '2026-11-01',
            ],
        ];

        // ── PERANGKAT JARINGAN ─────────────────────────────────────────────────
        $jaringan = [
            [
                'type' => 'router',
                'hostname' => 'RTR-KPP-CORE',
                'brand' => 'Mikrotik',
                'model' => 'RB4011iGS+RM',
                'serial_number' => 'SN-MTK-2021-RT01',
                'asset_tag' => 'AST-2024-201',
                'ip_address' => '10.9.1.1',
                'mac_address' => '2C:C8:1B:AB:CD:01',
                'location' => 'Lantai 1',
                'responsible_section' => 'Seksi IT / PDI (Ruang Server)',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2021-05-10',
                'warranty_expiry' => '2024-05-10',
                'notes' => 'Router utama. Gateway: 10.9.1.1/24.',
            ],
            [
                'type' => 'switch',
                'hostname' => 'SW-KPP-LT2-01',
                'brand' => 'Cisco',
                'model' => 'Catalyst 2960-X',
                'serial_number' => 'SN-CSC-2020-SW01',
                'asset_tag' => 'AST-2024-202',
                'ip_address' => '10.9.1.2',
                'mac_address' => '00:1E:BD:AB:CD:02',
                'location' => 'Lantai 2',
                'responsible_section' => 'Seksi IT / PDI (Ruang Server Mini)',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2020-11-20',
                'warranty_expiry' => '2023-11-20',
                'notes' => '24-port managed switch untuk lantai 2.',
            ],
            [
                'type' => 'switch',
                'hostname' => 'SW-KPP-LT1-01',
                'brand' => 'TP-Link',
                'model' => 'TL-SG108E',
                'serial_number' => 'SN-TPL-2022-SW01',
                'asset_tag' => 'AST-2024-203',
                'ip_address' => '10.9.1.3',
                'mac_address' => '98:DA:C4:AB:CD:03',
                'location' => 'Lantai 1',
                'responsible_section' => 'Seksi IT / PDI (Ruang Server)',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2022-01-10',
                'warranty_expiry' => '2025-01-10',
            ],
            [
                'type' => 'access-point',
                'hostname' => 'AP-KPP-LT1-01',
                'brand' => 'Ubiquiti',
                'model' => 'UniFi AP AC Pro',
                'serial_number' => 'SN-UBI-2022-AP01',
                'asset_tag' => 'AST-2024-204',
                'ip_address' => '10.9.1.11',
                'mac_address' => '78:8A:20:AB:CD:04',
                'location' => 'Lantai 1',
                'responsible_section' => 'Subbagian Umum (Lobby)',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2022-03-15',
                'warranty_expiry' => '2025-03-15',
            ],
            [
                'type' => 'access-point',
                'hostname' => 'AP-KPP-LT2-01',
                'brand' => 'Ubiquiti',
                'model' => 'UniFi AP AC Pro',
                'serial_number' => 'SN-UBI-2022-AP02',
                'asset_tag' => 'AST-2024-205',
                'ip_address' => '10.9.1.12',
                'mac_address' => '78:8A:20:AB:CD:05',
                'location' => 'Lantai 2',
                'responsible_section' => 'Subbagian Umum (Area Tengah)',
                'condition' => 'good',
                'status' => 'active',
                'purchase_date' => '2022-03-15',
                'warranty_expiry' => '2025-03-15',
            ],
            [
                'type' => 'access-point',
                'hostname' => 'AP-KPP-LT3-01',
                'brand' => 'Ubiquiti',
                'model' => 'UniFi AP AC Lite',
                'serial_number' => 'SN-UBI-2023-AP03',
                'asset_tag' => 'AST-2024-206',
                'ip_address' => '10.9.1.13',
                'mac_address' => '78:8A:20:AB:CD:06',
                'location' => 'Lantai 3',
                'responsible_section' => 'Pimpinan / Kepala Kantor',
                'condition' => 'excellent',
                'status' => 'active',
                'purchase_date' => '2023-01-08',
                'warranty_expiry' => '2026-01-08',
            ],
        ];

        // ── INSERT KOMPUTER ────────────────────────────────────────────────────
        foreach ($komputer as $i => $data) {
            $data['user_id'] = $i < count($userIds) ? $userIds[$i] : null;
            Device::create($data);
        }

        // ── INSERT PRINTER/SCANNER ─────────────────────────────────────────────
        foreach ($printers as $data) {
            $data['user_id'] = null; // Printer tidak diasign ke user tertentu
            Device::create($data);
        }

        // ── INSERT PERANGKAT JARINGAN ──────────────────────────────────────────
        foreach ($jaringan as $data) {
            $data['user_id'] = null;
            Device::create($data);
        }

        $this->command->info('DeviceSeeder: '.Device::count().' perangkat berhasil dibuat.');
    }
}
